# Generated by Django 4.0.3 on 2022-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkfilestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_status', models.CharField(choices=[('Success', 'Success'), ('Fail', 'Fail')], default='None', max_length=200)),
            ],
        ),
    ]
