# Generated by Django 4.0.3 on 2022-04-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkfilestatus',
        ),
    ]
